### ISSUE TITLE
Doesn't lint

### ISSUE THREAD

**Issue by jacekk015** [matthewmueller/atom-standard#3]
It formats perfectly but for the linting purposes I need to use linter-js-standard
Like shown below. Extra space and semicolon is linted by linter-js-standard.
Atom-standard linted only global
![zrzut ekranu z 2019-01-18 13-06-28](https://user-images.githubusercontent.com/14165726/51386344-617e0e80-1b22-11e9-81dd-4c9c9e671601.png)

**Comment by matthewmueller** [comment]
woah, i don't even remember making this. sorry i don't use atom anymore, but i'd happily accept a pr fixing this issue.

**Comment by jacekk015** [comment]
Thanks, but too much rework is needed.
